environment:
  enc_secret:
    secure: RpJa3MpXjYvN8clOld28OQRmiEofer3+x74FzE/pGcw=
  COVERALLS_REPO_TOKEN:
    secure: TJu0jqrb61YdQNdn7E/+qe9ApI2Apuj+Jfn789TuWy4jsojLhVM9nlvULwdy+Ypr

image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y
  - nuget install secure-file -ExcludeVersion
  - nuget install coveralls.net -ExcludeVersion
  - secure-file\tools\secure-file -decrypt signing_key.snk.enc -out Azuria/signing_key.snk -secret %enc_secret%

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

after_build:
  - ps: ./AppveyorPack.ps1

configuration: Appveyor

build:
  project: Azuria.sln
  verbosity: minimal
  
test_script:
  - ps: >-
      ./PrepareTestEnv.ps1
      
      cd ./Azuria.Test
    
      ../OpenCover/opencover.console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"xunit -appveyor -configuration Release" -filter:"+[*]* -[Azuria.Test*]* -[*]Azuria.Api.v1.DataModels*" -output:"coverage.xml"
      
      ../coveralls.net/tools/csmacnz.Coveralls.exe --opencover -i coverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor

artifacts:
  - path: '*.nupkg'
    name: Nuget Package

deploy:
  - provider: NuGet
    name: pre-release
    server: https://www.myget.org/F/infinitesoul/api/v2/package
    api_key:
        secure: /ZVEy+qqj8rmVkcPvuEuEsJCvEAG1chXaYhZCcLDEnhLIK+TkEIfGG/JDdMn7Qrf
    skip_symbols: false
    artifact: '*.nupkg'
    on:
        branch: master

  - provider: NuGet
    name: production
    api_key:
        secure: 8mKFfgwriyN1kzevZjQeDR8b3RdWPWnxDMZ2j5RZbQYquEhTo9YjPsNRaoqpWHaw
    skip_symbols: false
    artifact: '*.nupkg'
    on:
        appveyor_repo_tag: true