install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

configuration: Release

build:
  project: Azuria.sln
  verbosity: minimal

test: off