environment:
  enc_secret:
    secure: RpJa3MpXjYvN8clOld28OQRmiEofer3+x74FzE/pGcw=
  CODECOV_TOKEN:
    secure: vMjxysRiNi1LnEosRM5vPO8ZWw9jDlh2/WAdPRa5u4ZXqUkmP87x3WKXhCACmrCc

image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y
  - nuget install secure-file -ExcludeVersion
  - choco install codecov -y
  - secure-file\tools\secure-file -decrypt signing_key.snk.enc -out Azuria/signing_key.snk -secret %enc_secret%

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  
build_script:
  - msbuild Azuria.sln /verbosity:minimal /p:Configuration=Appveyor /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - ps: ./AppveyorPack.ps1
  
test_script:
  - cd Azuria.Test
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./coverage.xml /p:Exclude=\"[Azuria.Test*]*,[NUnit3.TestAdapter]*\"
  - codecov -f "coverage.xml" -t $CODECOV_TOKEN

artifacts:
  - path: '*.nupkg'
    name: Nuget Package
