environment:
  myget_key:
    secure: /ZVEy+qqj8rmVkcPvuEuEsJCvEAG1chXaYhZCcLDEnhLIK+TkEIfGG/JDdMn7Qrf

install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

after_build:
  - appveyor_pack.bat

on_success:
  - appveyor_push.bat

configuration: Release

build:
  project: Azuria.sln
  verbosity: minimal

artifacts:
  - path: '*.nupkg'
    name: Nuget Package