environment:
  enc_secret:
    secure: RpJa3MpXjYvN8clOld28OQRmiEofer3+x74FzE/pGcw=

image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt signing_key.snk.enc -out Azuria/signing_key.snk -secret %enc_secret%

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

after_build:
  - ps: ./AppveyorPack.ps1

configuration: Appveyor

build:
  project: Azuria.sln
  verbosity: minimal
  
test_script:
  - cmd: >-
      cd Azuria.Test
    
      dotnet xunit -appveyor -configuration Release

artifacts:
  - path: '*.nupkg'
    name: Nuget Package

deploy:
  - provider: NuGet
    name: pre-release
    server: https://www.myget.org/F/infinitesoul/api/v2/package
    api_key:
        secure: /ZVEy+qqj8rmVkcPvuEuEsJCvEAG1chXaYhZCcLDEnhLIK+TkEIfGG/JDdMn7Qrf
    skip_symbols: false
    artifact: '*.nupkg'
    on:
        branch: master

  - provider: NuGet
    name: production
    api_key:
        secure: 8mKFfgwriyN1kzevZjQeDR8b3RdWPWnxDMZ2j5RZbQYquEhTo9YjPsNRaoqpWHaw
    skip_symbols: false
    artifact: '*.nupkg'
    on:
        appveyor_repo_tag: true